name: .NET Publish

on:
  push:
    tags:
      - 'v*'  # Runs when a tag like v1.0.0 is pushed


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build package
        run: dotnet pack --configuration Release --output ./package

      - name: Publish to NuGet
        run: dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
